my_keywords = ['Artificial Intelligence',
	       'AI',
               'Google Glass',
               'Google Home',
               'Google',
               'Elon Musk',
               'raspberry pi',
               'Raspberry Pi',
               'European Union',
	       'EU',
               'Net Neutrality',
               'EFF', 
               'Open Rights', 
               'OpenRights',
               'Movies', 
               'movies', 
               'Top 10',
	       'vegan',
	       'Azure',
               ]
